### ISSUE TITLE
Struct page incorrect?

### ISSUE THREAD

**Issue by mmikeww** [HotKeyIt/AutoHotkey_H-Docs#1]
http://hotkeyit.github.io/v2/docs/commands/Struct.htm

> Struct, OutPutVar, Definition [,AddressToStructure, InitObject]
> 
> Command  Example: `Struct, pt, int x;y,% obj:={x:10,y:20}`
> Function Example: `pt := Struct("int x;y",{x:10,y:20})`

it looks like both of those examples show the `InitObject` as the 3rd parameter when it should be `AddressToStructure` parameter.. or maybe your definition is wrong?

**Comment by HotKeyIt** [comment]
There is a note in example for InitObject parameter:
pt:=Struct("x,y",{x:100,y:200}) ; When no AddressOfStructure is given, initobject must be the second parameter.

I will add it as Note on AddressToStructure and InitObject.

**Comment by mmikeww** [comment]
Ah I missed that, thanks
