### ISSUE TITLE
WinApi page docs say 'x' for uint instead of 'ui'

### ISSUE THREAD

**Issue by mmikeww** [HotKeyIt/AutoHotkey_H-Docs#10]
If you compare the definition table on these two pages, there are some extra entires on the WinApi page:

https://hotkeyit.github.io/v2/docs/commands/DynaCall.htm
https://hotkeyit.github.io/v2/docs/commands/WinApi.htm

The problem is, there are many "ui" parameters that you have listed for all of the WinApi functions at the bottom of the page. I'm guessing they should be uints, and the defintion table towards the top is outdated, and the DynaCall definition table is correct

**Comment by HotKeyIt** [comment]
x is special for WinApi because it behaves different for 64 and 32 bit.
ui is Uint on both 64 and 32 bit while x is Ushort on 32 bit.

**Comment by mmikeww** [comment]
Well I couldn't find one "x" in any functions in the whole WinApi 

And the "u" prefix wasn't mentioned in the table

**Comment by HotKeyIt** [comment]
"X" might be required in future.
I will add "u" to the table.
