### ISSUE TITLE
VarSetCapacity doc page was removed

### ISSUE THREAD

**Issue by mmikeww** [HotKeyIt/AutoHotkey_H-Docs#9]
[This forum thread](https://www.autohotkey.com/boards/viewtopic.php?f=67&t=70276) mentions some differences of VarSetCapacity in AHK_H vs AHK_L, and so I went to the docs to find out. 

It turns out, this link is broken:
https://github.com/HotKeyIt/AutoHotkey_H-Docs/blob/35207ddcab8f7cbc31e34186d92d650ab5578588/docs/AutoHotkey.htm#L255
because there is no longer a VarSetCapacity page in the v2 branch... it looks like you deleted it in the last commit.

The page above does give some brief info about VarSetCapacity changes, but I wanted to see the full docs page for more info

**Comment by HotKeyIt** [comment]
There was no additional information on that page, I linked it now to the VarSetCapacity page.
